name: OCEAN
favicon: null
layout_spectrum: 0.19375
typography_spectrum: 0.87504
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#c8d8f2'
    - '#040404'
    - '#7d9cb8'
    - '#3f4b20'
    - '#d57ac9'
  brandStrength: 0.5
  lightness: 0.5
  saturation: 0.5
  rhythmicContrast: 0.5
purpose: []
